Update backend test workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,6 +101,11 @@ jobs:
       - name: Test
         run: |
           ./mvnw clean verify -DskipTests=false -Dmaven.test.failure.ignore=true
+          if [ $? -ne 0 ]; then
+            echo "Tests failed"
+            exit 1
+          fi
+          echo "Tests passed"
 
   docker-push:
     name: Build and Push Docker Images
